name: responsi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  hive_generator: ^1.1.0
  flutter:
    sdk: flutter

  http: ^0.13.4
  shared_preferences: ^2.2.3
  hive_flutter: ^1.1.0
  hive: ^2.0.4
  path_provider: ^2.0.3
  flutter_web_auth: ^0.3.2
  http_proxy: ^1.2.2

dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
